// src/components/BackToTop.vue
<script setup lang="ts">
import { ArrowUpIcon } from "lucide-vue-next"

const isScrolledDown = ref(false)

onMounted(() => {
  const io = new IntersectionObserver(
    ([e]) => (isScrolledDown.value = !e.isIntersecting),
    { rootMargin: "900px 0px 0px 0px" }
  )

  io.observe(document.querySelector("[data-scroll-area]")!)
})

const scrollToTop = () => window.scrollTo(0, 0)
</script>

<template>
  <BaseButton
    reset
    class="z-[5] transition-[transform,opacity,background] duration-300 fixed flex items-center px-6 py-4 text-white bg-[var(--sp-button-active)] hover:bg-[var(--sp-button-active--hover)] rounded-md bottom-8 right-12 gap-x-2"
    :class="[
      !isScrolledDown
        ? 'opacity-0 pointer-events-none translate-y-2'
        : 'opacity-100 translate-y-0'
    ]"
    @click="scrollToTop"
  >
    <ArrowUpIcon :size="19" />
    <span> Back to top </span>
  </BaseButton>
</template>

// app/components/BackToTop.tsx
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faCaretUp } from "@fortawesome/free-solid-svg-icons";
import { useEffect } from "react";

export default function BackToTop() {

  useEffect(() => {
    const backToTop = document.getElementById("btt-btn");
    
    window.onscroll = () => {
      if (window.pageYOffset > 311) {
        backToTop.classList.add("btt-btn-show");
      } else {
        backToTop.classList.remove("btt-btn-show");
      }
    };
  }, []);

  return (
    <>
      <div className="fixed bottom-0 right-0 m-4">
        <button
          id="btt-btn"
          className="px-5 py-3 pointer-events-none opacity-0 shadow-md font-bold rounded-md transition-all translate-y-5 duration-300 text-xl text-center h-full w-full"
          onClick={() => window.scrollTo(0, 310)}
        >
          <FontAwesomeIcon icon={faCaretUp} size="lg" className="translate-y-[0.20rem]" />
          <span className="px-2">Back to top</span>
        </button>
      </div>
    </>
  );
};
