// app/src/components/BackToTop.tsx
import { useEffect, useState } from "react"
import { FontAwesomeIcon as FaIcon } from "@fortawesome/react-fontawesome"
import { faAngleUp } from "@fortawesome/free-solid-svg-icons"

export default function BackToTopButton() {
  // Display the button only if the user scrolls down 400px down
  const [show, setShow] = useState(
    "pointer-events-none opacity-0 translate-y-9"
  )

  const handleScroll = () => {
    window.scrollY > 400
      ? setShow("pointer-events-auto opacity-100 translate-y-0")
      : setShow("pointer-events-none opacity-0 translate-y-2")
  }

  useEffect(() => {
    window.addEventListener("scroll", handleScroll)
    return () => window.removeEventListener("scroll", handleScroll)
  }, [])

  return (
    <button
      className={`${show} fixed bottom-0 right-0 m-7 px-5 py-4 z-40 bg-blue-600 hover:bg-blue-700 text-white rounded-md shadow-lg transition-all duration-200 ease-in-out`}
      onClick={() => {
        window.scrollTo(0, 0)
      }}
    >
      <FaIcon icon={faAngleUp} size="lg" className="mr-4 ml-2" />
      <strong className="text-lg hidden md:inline-block">Back to top</strong>
    </button>
  )
}

// components/BackToTop.vue
<script setup lang="ts">
import { ArrowUpIcon } from "lucide-vue-next"

const isScrolledDown = ref(false)

onMounted(() => {
  const io = new IntersectionObserver(
    ([e]) => (isScrolledDown.value = !e.isIntersecting),
    { rootMargin: "900px 0px 0px 0px" }
  )

  io.observe(document.querySelector("[data-scroll-area]")!)
})

const scrollToTop = () => window.scrollTo(0, 0)
</script>

<template>
  <BaseButton
    reset
    class="transition-[transform,opacity,background] duration-300 fixed flex items-center px-6 py-4 text-white bg-blue-600 hover:bg-blue-700 rounded-md bottom-8 right-12 gap-x-2"
    :class="[
      !isScrolledDown
        ? 'opacity-0 pointer-events-none translate-y-2'
        : 'opacity-100 translate-y-0'
    ]"
    @click="scrollToTop"
  >
    <ArrowUpIcon :size="19" />
    <span> Back to top </span>
  </BaseButton>
</template>
