// app/src/pages/about.tsx
import BaseHead from "../components/BaseHead";

export default function AboutPage() {
  return (
    <>
      <BaseHead
        title="About this project - Searchpets"
        description="About the development of Searchpets"
      />
      <div className="my-0 mx-auto gap-4 max-w-[1440px] px-4 py-1">
        <h1 className="text-2xl font-bold">About this project</h1>
      </div>
    </>
  )
};

// src/pages/about.vue
<script setup lang="ts">
usePageMeta({
  title: "About Searchpets!",
  description:
    "Searchpets! is a project created by two idiots in Southeast Asia lol"
})
</script>

<template>
  <div>
    <ContentDoc
      tag="article"
      class="px-12 mx-auto space-y-4 prose-h2:mb-5 prose-h2:text-4xl prose-p:text-xl max-w-screen-2xl prose-headings:font-bold"
    />
  </div>
</template>
